"""phase_11_price_infrastructure

Revision ID: 7dbad9d06fb1
Revises: ac3c275604cd
Create Date: 2026-09-09 19:15:41.940041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dbad9d06fb1'
down_revision: Union[str, None] = 'ac3c275604cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('quote_currency', sa.String(length=8), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('recorded_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('rate_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rate > 0', name='ck_fx_rates_rate_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fx_rates_pair_recorded_at', 'fx_rates', ['base_currency', 'quote_currency', 'recorded_at'], unique=False)
    op.create_table('asset_price_configs',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('primary_provider', sa.String(length=64), nullable=True),
    sa.Column('primary_provider_symbol', sa.String(length=64), nullable=True),
    sa.Column('secondary_provider', sa.String(length=64), nullable=True),
    sa.Column('secondary_provider_symbol', sa.String(length=64), nullable=True),
    sa.Column('automated_fetching_enabled', sa.Boolean(), nullable=False),
    sa.Column('manual_override_enabled', sa.Boolean(), nullable=False),
    sa.Column('stale_threshold_minutes', sa.Integer(), nullable=True),
    sa.Column('lock_manual', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', name='uq_asset_price_configs_asset_id')
    )
    op.create_table('asset_prices',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('provider_symbol', sa.String(length=64), nullable=True),
    sa.Column('recorded_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('price_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_asset_prices_price_non_negative'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asset_prices_asset_id_recorded_at', 'asset_prices', ['asset_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_asset_prices_asset_id_recorded_at', table_name='asset_prices')
    op.drop_table('asset_prices')
    op.drop_table('asset_price_configs')
    op.drop_index('ix_fx_rates_pair_recorded_at', table_name='fx_rates')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
