"""phase 3 core portfolio schema

Revision ID: ac3c275604cd
Revises: 
Create Date: 2026-09-09 12:49:17.117733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac3c275604cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.Enum('STOCK', 'FUND', 'GOLD', 'CASH', 'SAVINGS', 'ETF', 'OTHER', name='asset_type'), nullable=False),
    sa.Column('market', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('strategy_bucket_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', name='uq_assets_symbol')
    )
    # NOTE: assets.strategy_bucket_id -> strategy_buckets.id is a circular
    # reference (assets -> strategy_buckets -> portfolio_configs -> assets).
    # The FK constraint is added below via ALTER TABLE, once strategy_buckets
    # exists, instead of inline here.
    op.create_table('portfolio_configs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('emergency_asset_id', sa.UUID(), nullable=True),
    sa.Column('emergency_excluded', sa.Boolean(), nullable=False),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emergency_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_buckets',
    sa.Column('portfolio_config_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_config_id'], ['portfolio_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_config_id', 'name', name='uq_strategy_bucket_portfolio_name')
    )
    op.create_foreign_key(
        'fk_assets_strategy_bucket_id_strategy_buckets',
        'assets', 'strategy_buckets',
        ['strategy_bucket_id'], ['id'],
        ondelete='SET NULL',
    )
    op.create_table('allocation_targets',
    sa.Column('portfolio_config_id', sa.UUID(), nullable=False),
    sa.Column('strategy_bucket_id', sa.UUID(), nullable=False),
    sa.Column('target_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('minimum_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('maximum_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('allow_new_buy', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('maximum_percent IS NULL OR (maximum_percent >= 0 AND maximum_percent <= 100)', name='ck_allocation_target_maximum_range'),
    sa.CheckConstraint('minimum_percent IS NULL OR (minimum_percent >= 0 AND minimum_percent <= 100)', name='ck_allocation_target_minimum_range'),
    sa.CheckConstraint('minimum_percent IS NULL OR maximum_percent IS NULL OR minimum_percent <= maximum_percent', name='ck_allocation_target_min_le_max'),
    sa.CheckConstraint('target_percent IS NULL OR (target_percent >= 0 AND target_percent <= 100)', name='ck_allocation_target_percent_range'),
    sa.ForeignKeyConstraint(['portfolio_config_id'], ['portfolio_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_bucket_id'], ['strategy_buckets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_config_id', 'strategy_bucket_id', name='uq_allocation_target_portfolio_bucket')
    )
    op.create_table('holdings',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('average_cost >= 0', name='ck_holdings_average_cost_non_negative'),
    sa.CheckConstraint('current_price >= 0', name='ck_holdings_current_price_non_negative'),
    sa.CheckConstraint('quantity >= 0', name='ck_holdings_quantity_non_negative'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', name='uq_holdings_asset_id')
    )
    op.create_table('portfolio_snapshots',
    sa.Column('portfolio_config_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_config_id'], ['portfolio_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_snapshots_config_snapshot_at', 'portfolio_snapshots', ['portfolio_config_id', 'snapshot_at'], unique=False)
    op.create_table('transactions',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', 'DIVIDEND', 'DEPOSIT', 'WITHDRAWAL', 'TRANSFER', name='transaction_type'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fees', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('transaction_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fees >= 0', name='ck_transactions_fees_non_negative'),
    sa.CheckConstraint('price >= 0', name='ck_transactions_price_non_negative'),
    sa.CheckConstraint('quantity >= 0', name='ck_transactions_quantity_non_negative'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_asset_id_transaction_date', 'transactions', ['asset_id', 'transaction_date'], unique=False)
    op.create_table('watchlist',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', name='uq_watchlist_asset_id')
    )
    op.create_table('alert_rules',
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('allocation_alert_enabled', sa.Boolean(), nullable=False),
    sa.Column('allocation_max_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('price_target_enabled', sa.Boolean(), nullable=False),
    sa.Column('price_target', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('dip_buy_enabled', sa.Boolean(), nullable=False),
    sa.Column('dip_buy_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('allocation_max_percent IS NULL OR (allocation_max_percent >= 0 AND allocation_max_percent <= 100)', name='ck_alert_rules_allocation_max_percent_range'),
    sa.CheckConstraint('dip_buy_price IS NULL OR dip_buy_price >= 0', name='ck_alert_rules_dip_buy_price_non_negative'),
    sa.CheckConstraint('price_target IS NULL OR price_target >= 0', name='ck_alert_rules_price_target_non_negative'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', name='uq_alert_rules_watchlist_id')
    )
    op.create_table('portfolio_snapshot_items',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('value >= 0', name='ck_snapshot_item_value_non_negative'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['portfolio_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'asset_id', name='uq_snapshot_item_snapshot_asset')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_snapshot_items')
    op.drop_table('alert_rules')
    op.drop_table('watchlist')
    op.drop_index('ix_transactions_asset_id_transaction_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_portfolio_snapshots_config_snapshot_at', table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_table('holdings')
    op.drop_table('allocation_targets')
    op.drop_constraint('fk_assets_strategy_bucket_id_strategy_buckets', 'assets', type_='foreignkey')
    op.drop_table('strategy_buckets')
    op.drop_table('portfolio_configs')
    op.drop_table('assets')
    # ### end Alembic commands ###
    # Native Postgres ENUM types are not dropped automatically by
    # op.drop_table() — drop them explicitly, after all tables using them
    # are gone, or a subsequent upgrade fails with "type already exists".
    op.execute("DROP TYPE IF EXISTS transaction_type")
    op.execute("DROP TYPE IF EXISTS asset_type")
