"""phase_19_notifications

Revision ID: c49911658945
Revises: 3210d10067b1
Create Date: 2026-09-11 20:13:09.196161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c49911658945'
down_revision: Union[str, None] = '3210d10067b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('PRICE_ALERT', 'ALLOCATION_ALERT', 'RECOMMENDATION_ALERT', 'PORTFOLIO_HEALTH_ALERT', name='notification_category'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'WARNING', 'INFO', name='notification_severity'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('target_category', sa.String(length=255), nullable=True),
    sa.Column('target_asset', sa.String(length=32), nullable=True),
    sa.Column('action', sa.Enum('REVIEW_DISTRIBUTION', 'REVIEW_RECOMMENDATIONS', 'OPEN_ASSET', name='notification_action'), nullable=True),
    sa.Column('read_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_source_id'), 'notifications', ['source_id'], unique=False)
    op.create_index('uq_notifications_source_id_active', 'notifications', ['source_id'], unique=True, postgresql_where=sa.text('resolved_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_notifications_source_id_active', table_name='notifications', postgresql_where=sa.text('resolved_at IS NULL'))
    op.drop_index(op.f('ix_notifications_source_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
