// Zero-dependency structural tests for the Capacitor shell (Phase 22),
// using Node's built-in test runner so this package needs no test
// framework of its own. Run with `npm test` (see package.json).
import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { execSync } from "node:child_process";

const EXPECTED_APP_ID = "com.mizan.app";
const EXPECTED_APP_NAME = "MIZAN";

function loadConfig() {
  // capacitor.config.ts is an ES module; compile it to JS on the fly so
  // this test needs no extra build step or dependency beyond `typescript`
  // (already a devDependency for `cap add`/`cap sync` to run at all).
  const js = execSync("npx tsc capacitor.config.ts --module esnext --target es2020 --outDir /tmp/cap-config-test", {
    cwd: import.meta.dirname,
  });
  void js;
  return import("file:///tmp/cap-config-test/capacitor.config.js").then((m) => m.default);
}

// --- A/B/C: Capacitor config is valid, with the correct app identity -----

test("capacitor.config.ts declares the expected app id and name", async () => {
  const config = await loadConfig();
  assert.equal(config.appId, EXPECTED_APP_ID);
  assert.equal(config.appName, EXPECTED_APP_NAME);
});

test("capacitor.config.ts bundles the frontend static export rather than loading a remote URL", async () => {
  const config = await loadConfig();
  assert.equal(config.webDir, "../../frontend/out");
  // No server.url: this ships as "native shell + bundled frontend", not a
  // thin wrapper around a live website -- see DECISIONS.md, Phase 22.
  assert.equal(config.server?.url, undefined);
});

test("capacitor.config.ts never weakens Android network security", async () => {
  const config = await loadConfig();
  assert.equal(config.android?.allowMixedContent, false);
});

// --- F: native project identity is consistent with capacitor.config.ts ---
// Best-effort: android/ and ios/ are generated by `cap add` and gitignored
// (see .gitignore), so a fresh checkout genuinely won't have them until
// that's run. Skip rather than fail when they're absent.

test("Android project applicationId/appName match capacitor.config.ts", async (t) => {
  if (!existsSync("android/app/build.gradle")) {
    t.skip("android/ not generated in this checkout -- run `npx cap add android` first");
    return;
  }
  const gradle = readFileSync("android/app/build.gradle", "utf-8");
  assert.match(gradle, new RegExp(`applicationId "${EXPECTED_APP_ID}"`));
  const strings = readFileSync("android/app/src/main/res/values/strings.xml", "utf-8");
  assert.match(strings, new RegExp(`<string name="app_name">${EXPECTED_APP_NAME}</string>`));

  const manifest = readFileSync("android/app/src/main/AndroidManifest.xml", "utf-8");
  // Never permit cleartext (plaintext HTTP) traffic in the shipped app.
  assert.doesNotMatch(manifest, /usesCleartextTraffic\s*=\s*"true"/);
});

test("iOS project bundle identifier and display name match capacitor.config.ts", async (t) => {
  if (!existsSync("ios/App/App.xcodeproj/project.pbxproj")) {
    t.skip("ios/ not generated in this checkout -- run `npx cap add ios` first");
    return;
  }
  const pbxproj = readFileSync("ios/App/App.xcodeproj/project.pbxproj", "utf-8");
  assert.match(pbxproj, new RegExp(`PRODUCT_BUNDLE_IDENTIFIER = ${EXPECTED_APP_ID.replace(/\./g, "\\.")};`));

  const plist = readFileSync("ios/App/App/Info.plist", "utf-8");
  assert.match(plist, new RegExp(`<string>${EXPECTED_APP_NAME}</string>`));

  // No ATS exceptions permitting arbitrary/insecure loads in the shipped app.
  assert.doesNotMatch(plist, /NSAllowsArbitraryLoads/);
});
